wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.5
    framework: huggingface
    huggingface_version: 4.48.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739279270
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      3:
      - 4
      - 23
      - 42
      - 55
      4: 3.11.11
      5: 0.19.5
      6: 4.48.3
      8:
      - 5
      13: linux-x86_64
